allAtm = [
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Daytime/Spectral Sunshine/705 Boi Valley.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Daytime/Spectral Sunshine/706 Romania.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Daytime/Spectral Sunshine/708 Argentina.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Daytime/Spectral Sunshine/Bisbee.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Daytime/Spectral Sunshine/CS20 11 Cumulus & Shadows.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Daytime/Spectral Sunshine/High Altitude.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Daytime/Spectral Sunshine/JB_007.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Daytime/Spectral Sunshine/Monterrey.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Daytime/Spectral Sunshine/N Barcelona.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Daytime/Spectral Sunshine/N Classic Day.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Daytime/Spectral Sunshine/N SD10 23 Danger in the Air.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Daytime/Spectral Sunshine/N SD45 02 Cloud Front.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Daytime/Spectral Sunshine/N SD50 27 Sunny Seaside.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Daytime/Spectral Sunshine/Oakland.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Daytime/Spectral Sunshine/Santa Monica.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Daytime/Spectral Sunshine/SD15 25 Fair Weather.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Daytime/Spectral Sunshine/SD25 17 Cold Spring.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Daytime/Spectral Sunshine/SD30 24 The Big Ones.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Daytime/Spectral Sunshine/SD35 18 On the Move.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Daytime/Spectral Sunshine/SD40 06 Angel Hair.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Daytime/Spectral Sunshine/SD45 02 Cloud Front.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Daytime/Spectral Sunshine/Tel Aviv.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Daytime/Spectral Sunshine/Venice.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Effects/Sci-Fi/01 It came from East.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Effects/Sci-Fi/01mSulfuric.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Effects/Sci-Fi/02_Saturne.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Effects/Sci-Fi/02_Venus.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Effects/Sci-Fi/10_Alien Ballet.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Effects/Sci-Fi/10_Strange Patterns.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Effects/Sci-Fi/11_Busy Sepia Aliens.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Effects/Sci-Fi/Alien_Green_3_~~.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Effects/Sci-Fi/Martian Red.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Effects/Sci-Fi/NI10 30 White Dwarf.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Effects/Sci-Fi/Sulfuric Spectral.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Effects/Sci-Fi/Synthetic.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Others/Spectral/Arabian_nights0_57_~~.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Others/Spectral/Arabian_nights_57_~~.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Others/Spectral/Foggy_night_57_~~.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Others/Spectral/Full_moon_57_~~.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Others/Spectral/It_s_happenning_now_57_~~.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Others/Spectral/L_heure_bleue_57_~~.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Others/Spectral/November_the_12th_57_~~.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Others/Spectral/Starry_night_57_~~.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Others/Spectral/Sunday_morning_57_~~.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Others/Spectral/Vesterolen_57_~~.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Others/Spectral/Winter_Mist_Vue_53_~~.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Simple Sunset/Mongolian_Dusk_3_~~.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Simple Sunset/Springtime_Dawn_3_~~.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Spectral Sunsets/01_Optimistic Dawn.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Spectral Sunsets/701 Dingle.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Spectral Sunsets/702 Cevennes.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Spectral Sunsets/703 Iditarod.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Spectral Sunsets/704 Jaisalmer.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Spectral Sunsets/705 Drakensberg.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Spectral Sunsets/706 Nakuru.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Spectral Sunsets/707 Aix en Provence.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Spectral Sunsets/708 Malacca.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Spectral Sunsets/709 Great Ocean Road.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Spectral Sunsets/Boulder Sunset.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Spectral Sunsets/CS05 01 Pink Evening.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Spectral Sunsets/Hawaii Gold.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Spectral Sunsets/N SS65 28 Classic Sunset.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Spectral Sunsets/Spectral Sunset.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Spectral Sunsets/SS05 18 BasicSunset.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Spectral Sunsets/SS05 19 Good Night.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Spectral Sunsets/SS10 20 Heroic Sunset.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Spectral Sunsets/SS15 21 Fantasy Sunset.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Spectral Sunsets/SS50 03 Lead & Gold.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Spectral Sunsets/SS55 04 Dying Sun-2.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Spectral Sunsets/SS60 08 Life and Death-2.atm',  
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Sunset/Just_before_Sunset_3_~~.atm', 
'/Users/glen/Documents/e-on software/Vue xStream 2014/Atmospheres/Sunset/Sunset/Summer_Dawn_3_~~.atm']

atmLength = len(allAtm)
for i in range(0, atmLength):
	LoadAtmosphere(allAtm[i])
	print ("Loading Atmosphere : " + allAtm[i])
	Refresh()
	Render()
	imgFile = ('/Shared3/projects/Assets/sourceimages/imageBasedLighting/sky/Vue/Sky' + str(i) + '.exr')
	print ("Saving Image : " + imgFile)
	SaveColorPicture(imgFile) 
